import { Company, Experience, Skill } from "./types";

const Scottsdale = "Scottsdale, AZ";

export const ImagineLearning: Company = {
  name: "Imagine Learning",
  location: Scottsdale,
};

export const SavvyTrader: Company = {
  name: "Savvy Trader",
  location: Scottsdale,
};

export const GitKraken: Company = {
  name: "GitKraken",
  location: Scottsdale,
};

export const SandhillsPublishing: Company = {
  name: "Sandhills Publishing",
  location: Scottsdale,
};

export const CRC: Company = {
  name: "CRC Information Systems",
  location: Scottsdale,
};

export const bigFivePersonalityScores = [
  { attribute: "Openness", rating: 79 },
  { attribute: "Conscientiousness", rating: 60 },
  { attribute: "Extroversion", rating: 75 },
  { attribute: "Agreeableness", rating: 65 },
  { attribute: "Neuroticism", rating: 40 },
];

export const experiences: Experience[] = [
  {
    startDate: new Date("10/1/2023"),
    startDisplay: "10/2023",
    title: "Senior Software Engineer",
    company: ImagineLearning,
    color: "#66CCFF",
    achievements: [
      "Build and maintain SaaS products with React and TypeScript",
      "Introduced Storybook, Prettier, Cypress, and more to team",
      "Develop and maintain micro front-ends",
      "Provide best practice guidance on Git, React, and TypeScript",
      "Turn loose requirements and Figma mocks into reality",
      "Integrate with GraphQL APIs and REST APIs",
      "Create highly reusable, robust, scalable, testable code",
    ],
    skills: [
      Skill.React,
      Skill.TypeScript,
      Skill.JavaScript,
      Skill.CSharp,
      Skill.SQL,
      Skill.EventDrivenArchitecture,
      Skill.EndToEndTesting,
      Skill.Cypress,
      Skill.Jest,
      Skill.UnitTesting,
      Skill.Redux,
      Skill.TailwindCSS,
      Skill.HTML,
      Skill.CSS,
      Skill.SASS,
      Skill.Git,
      Skill.Mentorship,
      Skill.Leadership,
      Skill.LargeScaleSystems,
      Skill.APIDevelopment,
      Skill.APIIntegration,
      Skill.REST,
      Skill.GraphQL,
      Skill.CICD,
      Skill.TeamworkandCollaboration,
      Skill.CodeReviews,
      Skill.WebAppDevelopment,
      Skill.AgileScrum,
      Skill.FrontEnd,
      Skill.Webpack,
      Skill.Storybook,
      Skill.Figma,
      Skill.Jira,
      Skill.BackEnd,
    ],
  },
  {
    startDate: new Date("12/1/2022"),
    startDisplay: "12/2022",
    title: "Senior Software Engineer",
    company: SavvyTrader,
    color: "#3399FF",
    achievements: [
      "Build and maintain React and TypeScript FE (a portfolio sharing platform)",
      "Build and deploy mobile apps with Capacitor JS",
      "Build and maintain TypeScript and Node.js BE using Dynamo and SQL databases",
      "BE is 100% microservice architecture",
      "Use many AWS solutions (Lambda, CloudWatch, RDS, DynamoDB, S3, EventBridge, etc)",
      "Architected multiple differentiator AI features using OpenAI/OpenAPI",
      "Integrate with both internal and external APIs",
      "Create highly reusable, robust, scalable, testable code",
      "Data visualization using Highcharts, Victory Charts",
    ],
    skills: [
      Skill.React,
      Skill.TypeScript,
      Skill.JavaScript,
      Skill.SQL,
      Skill.DynamoDB,
      Skill.AWS,
      Skill.EventDrivenArchitecture,
      Skill.EndToEndTesting,
      Skill.Jest,
      Skill.UnitTesting,
      Skill.Redux,
      Skill.HTML,
      Skill.CSS,
      Skill.SASS,
      Skill.Git,
      Skill.Leadership,
      Skill.LargeScaleSystems,
      Skill.APIDevelopment,
      Skill.APIIntegration,
      Skill.REST,
      Skill.StartupEnvironment,
      Skill.AI,
      Skill.ChatGPTFeatures,
      Skill.MUI,
      Skill.CICD,
      Skill.TeamworkandCollaboration,
      Skill.CodeReviews,
      Skill.WebAppDevelopment,
      Skill.MobileAppDevelopment,
      Skill.CapacitorJS,
      Skill.NodeJS,
      Skill.FrontEnd,
      Skill.BackEnd,
      Skill.Webpack,
      Skill.Storybook,
    ],
  },
  {
    startDate: new Date("03/1/2022"),
    startDisplay: "03/2022",
    endDate: new Date("12/1/2022"),
    endDisplay: "12/2022",
    title: "Senior Software Engineer",
    company: ImagineLearning,
    color: "#0066CC",
    achievements: [
      "Use React and TypeScript to build and maintain education software",
      "Integrate with third party or internal APIs (both GraphQL and REST)",
      "Create highly reusable, robust, scalable, testable code",
      "Mentor junior developers",
      "Participate in high level architectural discussions about direction of engineering",
    ],
    skills: [
      Skill.React,
      Skill.TypeScript,
      Skill.JavaScript,
      Skill.CSharp,
      Skill.SQL,
      Skill.EventDrivenArchitecture,
      Skill.EndToEndTesting,
      Skill.Cypress,
      Skill.Jest,
      Skill.UnitTesting,
      Skill.Redux,
      Skill.TailwindCSS,
      Skill.HTML,
      Skill.CSS,
      Skill.SASS,
      Skill.Git,
      Skill.Mentorship,
      Skill.Leadership,
      Skill.LargeScaleSystems,
      Skill.APIDevelopment,
      Skill.APIIntegration,
      Skill.REST,
      Skill.GraphQL,
      Skill.CICD,
      Skill.TeamworkandCollaboration,
      Skill.CodeReviews,
      Skill.WebAppDevelopment,
      Skill.AgileScrum,
      Skill.FrontEnd,
      Skill.Webpack,
      Skill.Storybook,
      Skill.Figma,
      Skill.Jira,
      Skill.BackEnd,
    ],
  },
  {
    startDate: new Date("8/1/2019"),
    startDisplay: "08/2019",
    endDate: new Date("03/1/2022"),
    endDisplay: "03/2022",
    title: "Software Engineer II",
    company: GitKraken,
    color: "#99CCFF",
    achievements: [
      "Built and maintained a world class Git GUI (desktop app) using React, JavaScript + Flow, Node.js, Electron, and TypeScript",
      "Integrated with numerous Git provider APIs",
      "Developed and maintained an extensive, multi-process spanning Redux system",
      "Spearheaded refactor from async actions to Redux Saga",
      "Mentored junior developers and interns",
      "Left as one of the top 3 all time contributors",
    ],
    skills: [
      Skill.React,
      Skill.TypeScript,
      Skill.JavaScript,
      Skill.EventDrivenArchitecture,
      Skill.EndToEndTesting,
      Skill.Cypress,
      Skill.AWS,
      Skill.Jest,
      Skill.UnitTesting,
      Skill.Redux,
      Skill.ReduxSaga,
      Skill.Mentorship,
      Skill.Leadership,
      Skill.HTML,
      Skill.CSS,
      Skill.SASS,
      Skill.Git,
      Skill.APIDevelopment,
      Skill.APIIntegration,
      Skill.StartupEnvironment,
      Skill.REST,
      Skill.GraphQL,
      Skill.CICD,
      Skill.TeamworkandCollaboration,
      Skill.CodeReviews,
      Skill.NodeJS,
      Skill.DesktopAppDevelopment,
      Skill.AgileScrum,
      Skill.FrontEnd,
      Skill.BackEnd,
      Skill.Webpack,
      Skill.Electron,
      Skill.MongoDB,
      Skill.Figma,
    ],
  },
  {
    startDate: new Date("03/1/2018"),
    startDisplay: "03/2018",
    endDate: new Date("08/1/2019"),
    endDisplay: "08/2019",
    title: "Software Engineer",
    company: SandhillsPublishing,
    color: "#3366FF",
    achievements: [
      "Built and maintained SaaS and internal solutions with JavaScript, VB.NET, C#.NET, SQL, and MVC architectures",
      "Mentored and onboarded multiple engineers",
      "Developed an internal efficiency boosting Chrome Extension using JavaScript",
    ],
    skills: [
      Skill.JavaScript,
      Skill.CSharp,
      Skill.VBNET,
      Skill.ASPNET,
      Skill.MVC,
      Skill.SQL,
      Skill.HTML,
      Skill.CSS,
      Skill.Mentorship,
      Skill.LargeScaleSystems,
      Skill.APIIntegration,
      Skill.APIDevelopment,
      Skill.REST,
      Skill.TeamworkandCollaboration,
      Skill.CodeReviews,
      Skill.WebAppDevelopment,
      Skill.StoredProcedures,
      Skill.AgileScrum,
      Skill.FrontEnd,
      Skill.BackEnd,
    ],
  },
  {
    startDate: new Date("01/1/2017"),
    startDisplay: "01/2017",
    endDate: new Date("03/1/2018"),
    endDisplay: "03/2018",
    title: "Software Engineer",
    company: CRC,
    color: "#003399",
    achievements: [
      "Built and maintained code in C#.NET, SQL, and VB6",
      "Customer facing updates and support",
      "Fixed numerous field and internal bugs",
    ],
    skills: [
      Skill.VB6,
      Skill.VBNET,
      Skill.ASPNET,
      Skill.SQL,
      Skill.HTML,
      Skill.CSS,
      Skill.TeamworkandCollaboration,
      Skill.CodeReviews,
      Skill.StoredProcedures,
      Skill.FrontEnd,
      Skill.StartupEnvironment,
    ],
  },
].reverse();
